### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by zqx951102** [ShuangLI59/Person-Search-with-Natural-Language-Description#10]
您好，请问这个数据集如何去获取？ 找了很长时间，也没找到开源的数据集，谢谢了 是需要邮箱吗？ 1978457270@qq.com
 我记得以前用邮箱联系过您，寻求数据集，可是一直没回复。

**Comment by ppsychoo** [comment]
同问，请问你拿到数据集了吗？

**Comment by zqx951102** [comment]
我已经拿到啦 作者回我了 我就可以下载了

**Comment by ppsychoo** [comment]
那你能发我一份数据集吗？作者一直没有回复我，我的邮箱是2337537323@qq.com，谢谢！！！

**Comment by ShuangLI59** [comment]
Thank you very much for your interest. Due to licensing issues, could you please resend this email using your university email? Please do not redistribute this dataset and do not use it for commercial purposes!

**Comment by 1390806607** [comment]
@zqx951102  Hello, please send the data set to me at my email 1390806607@qq.com

**Comment by Jinpeng360** [comment]
Could you please send me the dataset to my email 1211003009@cnu.edu.cn . That is my university email. Thank you so much!

**Comment by yuxuan123lucky** [comment]
> 我已经得到啦作者回我了我就可以下载了
请问您可以给我发一份吗我的邮箱是zhaoyuxuan1@sxu.edu.cn非常感谢！
