### ISSUE TITLE
Which dataSet did you use?

### ISSUE THREAD

**Issue by LeeRock** [ShuangLI59/Person-Search-with-Natural-Language-Description#2]
**# as you mentioned:**
 "Request the dataset from sli [at] ee.cuhk.edu.hk or xiaotong [at] ee.cuhk.edu.hk (academic only)."
**# Person Re-identification Datasets include lots of dataset including:**

- VIPeR | 2007 | 632 | 2 | 1264 | Hand | 128X48 |   |   |  
- ETH1,2,3 | 2007 | 85,35,28 | 1 | 8580 | Hand | Vary | ✔ | ✔ | ✔
- QMUL iLIDS | 2009 | 119 | 2 | 476 | Hand | Vary | ✔ |   |  
- GRID | 2009 | 1025 | 8 | 1275 | Hand | Vary |   |   |  
- CAVIAR4ReID | 2011 | 72 | 2 | 1220 | Hand | Vary | ✔ |   |  
- 3DPeS | 2011 | 192 | 8 | 1011 | Hand | Vary | ✔ |   | ✔*
- PRID2011 | 2011 | 934 | 2 | 24541 | Hand | 128X64 | ✔ | ✔ | ✔*
- V47 | 2011 | 47 | 2 | 752 | Hand | Vary | ✔ |   | ✔
- WARD | 2012 | 70 | 3 | 4786 | Hand | 128X48 | ✔ | ✔ |  
- SAIVT-Softbio | 2012 | 152 | 8 | 64472 | Hand | Vary | ✔ | ✔ | ✔
- CUHK01 | 2012 | 971 | 2 | 3884 | Hand | 160X60 | ✔ |   |  
- CUHK02 | 2013 | 1816 | 10(5 pairs) | 7264 | Hand | 160X60 | ✔ |   |  
- CUHK03 | 2014 | 1467 | 10(5 pairs) | 13164 | Hand/DPM | Vary | ✔ |   |  
- RAiD | 2014 | 43 | 4 | 6920 | Hand | 128X64 | ✔ |   |  
- iLIDS-VID | 2014 | 300 | 2 | 42495 | Hand | Vary | ✔ | ✔ |  
- MPR Drone | 2014 | 84 | 1 |   | Pyramid Features(ACF) | Vary | ✔ |   | ✔
- HDA Person Dataset | 2014 | 53 | 13 | 2976 | Hand/Pyramid Features(ACF) | Vary | ✔ | ✔ | ✔
- Shinpuhkan Dataset | 2014 | 24 | 16 |   | Hand | 128X48 | ✔ | ✔ |  
- CASIA Gait Database B | 2015(*see below) | 124 | 11 |   | Background subtraction | Vary | ✔ | ✔ | ✔
- Market1501 | 2015 | 1501 | 6 | 32217 | Hand/DPM | 128X64 | ✔ |   |  
- PRW | 2016 | 932 | 6 | 34304 | Hand | vary | ✔ |   | ✔
- Large scale person search | 2016 | 11934s | - | 34574 | Hand | vary |   |   | ✔
- MARS | 2016 | 1261 | 6 | 1191003 | DPM+GMMCP | 256X128 | ✔ | ✔ |  
- DukeMTMC-reID | 2017 | 1812 | 8 | 36441 | Hand | Vary | ✔ |   | ✔
- DukeMTMC4ReID | 2017 | 1852 | 8 | 46261 | Doppia | Vary | ✔ |   | ✔
- Airport | 2017 | 9651 | 6 | 39902 | ACF | 128X64 | ✔ |

**Comment by ShuangLI59** [comment]
We collect a new dataset, please send an email to sli@ee.cuhk.edu.hk if you need the dataset. The dataset is used for academic purpose only.
