### ISSUE TITLE
the sentence descriptions are not 80412?

### ISSUE THREAD

**Issue by 136823xuewei** [ShuangLI59/Person-Search-with-Natural-Language-Description#4]
hello, thank  you very much for providing your dataset. I have a question about the dataset. In this paper, it says there are 40206 images and 80412 sentence descriptions, however the result of my experiment shows that there are 40206 images and 80440 sentence descriptions. If i compare with your work, how i to deal with dataset? Should i use all dataset or remove the extra sentences? Thans.

**Comment by ShuangLI59** [comment]
Yes, only several images have 4 descriptions, you can use the first two sentences. This won't influence the final results much.
