### ISSUE TITLE
how can I get the dataset?

### ISSUE THREAD

**Issue by Fly2flies** [ShuangLI59/Person-Search-with-Natural-Language-Description#7]
Thanks for sharing such a good work. I want to know how I can get the access to the data? still send an email to these two mail address?

**Comment by Teja-P-oss** [comment]
> Thanks for sharing such a good work. I want to know how I can get the access to the data? still send an email to these two mail address?

Same problem for me either. Have  you figured it out yet? please let me know

**Comment by deropty** [comment]
> Thanks for sharing such a good work. I want to know how I can get the access to the data? still send an email to these two mail address?

Same problem.

**Comment by 1443958306** [comment]
Same problem

**Comment by rookiecsq** [comment]
Same problem
